//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.34014
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace turnir.Properties {
    using System;
    
    
    /// <summary>
    ///   Класс ресурса со строгой типизацией для поиска локализованных строк и т.д.
    /// </summary>
    // Этот класс создан автоматически классом StronglyTypedResourceBuilder
    // с помощью такого средства, как ResGen или Visual Studio.
    // Чтобы добавить или удалить член, измените файл .ResX и снова запустите ResGen
    // с параметром /str или перестройте свой проект VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Возвращает кэшированный экземпляр ResourceManager, использованный этим классом.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("turnir.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Перезаписывает свойство CurrentUICulture текущего потока для всех
        ///   обращений к ресурсу с помощью этого класса ресурса со строгой типизацией.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;Titles&gt;
        ///  &lt;Title coef=&quot;6&quot; short=&quot;-&quot; full=&quot;юноши и девушки без разряда&quot;&gt;
        ///  &lt;/Title&gt;
        ///  &lt;Title coef=&quot;5&quot; short=&quot;3 ю.&quot; full=&quot;3 юношеский разряд&quot;&gt;
        ///    &lt;Norm coef=&quot;6&quot;&gt;60&lt;/Norm&gt;
        ///    &lt;Norm coef=&quot;5&quot;&gt;50&lt;/Norm&gt;
        ///    &lt;Norm coef=&quot;4&quot;&gt;35&lt;/Norm&gt;
        ///    &lt;Norm coef=&quot;3&quot;&gt;20&lt;/Norm&gt;
        ///    &lt;Norm coef=&quot;2&quot;&gt;5&lt;/Norm&gt;
        ///  &lt;/Title&gt;
        ///  &lt;Title coef=&quot;4&quot; short=&quot;2 ю.&quot; full=&quot;2 юношеский разряд&quot;&gt;
        ///    &lt;Norm coef=&quot;6&quot;&gt;75&lt;/Norm&gt;
        ///    &lt;Norm coef=&quot;5&quot;&gt;65&lt;/Norm&gt;
        ///    &lt;Norm coef=&quot;4&quot;&gt;50&lt;/Norm&gt;
        ///    &lt;Norm coef=&quot; [остаток строки не уместился]&quot;;.
        /// </summary>
        internal static string norms {
            get {
                return ResourceManager.GetString("norms", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на -,3 ю.,2 ю.,1 ю.,3,2,1,кмс,мс.
        /// </summary>
        internal static string Titles {
            get {
                return ResourceManager.GetString("Titles", resourceCulture);
            }
        }
    }
}
